name: save pr poison

on: pull_request_target

jobs:
  poison:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Save pr poison
        uses: actions/cache/save@v2
        with:
          path: |
            poison
          key: poison_key
