name: wr

on:
  workflow_run:
    workflows: [pr]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          fallocate -l 10G file10GB
          echo "pr" > poison
      - name: nuke cache
        uses: actions/cache/save@v4
        with:
          path: |
            file10GB
          key: something
      - name: Save main poison
        uses: actions/cache/save@v4
        with:
          path: |
            poison
          key: poison_key
