name: wr

on:
  workflow_dispatch:
  workflow_run:
    workflows: [pr]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          now=$(date)
          echo "$now" > poison
      - name: Save main poison
        uses: actions/cache/save@v4
        with:
          path: |
            poison
          key: poison_key
